version: "3.6"
volumes:
  shared-workspace:
    name: "hadoop-distributed-file-system"
    driver: local
services:
  jupyterlab:
    image: jupyterlab
    container_name: jupyterlab
    ports:
      - 8888:8888
    volumes:
      - ./shared-workspace:/opt/workspace
  jupyter-spark-master:
    image: jupyter-spark-master
    container_name: jupyter-spark-master
    ports:
      - 4040:4040
      - 8080:8080
      - 7077:7077
    volumes:
      - ./shared-workspace:/opt/workspace
  jupyter-spark-worker-1:
    image: jupyter-spark-worker
    container_name: jupyter-spark-worker-1
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
    ports:
      - 8081:8081
    volumes:
      - ./shared-workspace:/opt/workspace
    depends_on:
      - jupyter-spark-master
  jupyter-spark-worker-2:
    image: jupyter-spark-worker
    container_name: jupyter-spark-worker-2
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1g
    ports:
      - 8082:8081
    volumes:
      - shared-workspace:/opt/workspace
    depends_on:
      - jupyter-spark-master
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - "TZ=Europe/Amsterdam"
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
    ports:
      - "5432:5432"
    volumes:
      - "./shared-workspace/sql:/docker-entrypoint-initdb.d"
